version: 2
jobs:
  build:
    working_directory: ~/crashCourseTestRepo
    docker:
      - image: maven:3.5.0-jdk-9

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn clean test