version: 2.1

executors:
    my-executor:
        docker:
            - image: circleci/openjdk:11.0.3-jdk-stretch
        environment:
            # Customize the JVM maximum heap limit
            MAVEN_OPTS: -Xmx3200m
            _JAVA_OPTIONS: "-Xmx3g"

orbs:
    slack: circleci/slack@3.4.2

commands:
    setup-project:
        description: "Setup project"
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies{{ checksum "pom.xml" }}
                    - v1-dependencies-
            - run: mvn dependency:go-offline
            - save_cache:
                paths:
                    - ~/.m2
                key: v1-dependencies-{{ checksum "pom.xml" }}

            -   run:
                    name: Run tests
                    command: mvn integration-test

jobs:
    general_job:
        executor: my-executor
        steps:
            - setup-project

workflows:
    version: 2.1
    build:
        jobs:
            - general_job