version: 2.1
jobs:
  first-job:
    docker:
      - image: maven:3.6.3-jdk-11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Run tests
          command: >
            mvn
            -Dsuite=testng
            clean test
workflows:
  version: 2.1
  test_workflow:
    jobs:
      - first-job