version: 2.1

executors:
    my-executor:
        docker:
            - image: circleci/openjdk:14-jdk-buster
        working_directory: ~/repo
        environment:
            # Customize the JVM maximum heap limit
            MAVEN_OPTS: -Xmx3200m

commands:
    setup-project:
        description: "Setup project"
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "pom.xml" }}
                      - v1-dependencies-
            - run: mvn clean install
            - run: mvn dependency:go-offline
            - save_cache:
                  paths:
                      - ~/.m2
                  key: v1-dependencies-{{ checksum "pom.xml" }}
            - store_test_results:
                  path: target/surefire-reports
            - store_artifacts:
                  path: target/crashCourseTestRepo-1.0-SNAPSHOT.jar
            - run: mvn test

jobs:
    general_job:
        executor: my-executor
        steps:
            - setup-project

workflows:
    version: 2.1
    build:
        jobs:
            - general_job