version: 2.1

executors:
    my-executor:
        docker:
            #- image: maven:3.6.3-jdk-11
            - image: circleci/openjdk:9.0.4-jdk
            - image: selenium/standalone-chrome:3.11.0
        environment:
            # Customize the JVM maximum heap limit
            MAVEN_OPTS: -Xmx3200m

commands:
    setup-project:
        description: "Setup project"
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies{{ checksum "pom.xml" }}
                    - v1-dependencies-
            - run: mvn install
            - run: mvn dependency:go-offline
            - save_cache:
                paths:
                    - ~/.m2
                key: v1-dependencies-{{ checksum "pom.xml" }}
            - store_test_results:
                path: target/surefire-reports
            - store_artifacts:
                path: target/crashCourseTestRepo-1.0-SNAPSHOT.jar

    selenium-server:
        description: "Run selenium server"
        steps:
            - run: mkdir test-reports
            - run:
                name: Download Selenium
                command: |
                    curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
            - run:
                name: Start Selenium
                command: |
                    java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
                background: true
    suite:
        description: "Run suite"
        steps:
            - run:
                name: Run tests
                command: mvn clean test

jobs:
    general_job:
        executor: my-executor
        steps:
            - setup-project
            - selenium-server
            - suite

workflows:
    version: 2.1
    build:
        jobs:
            - general_job